#!/usr/bin/env python3
"""Turn the generated whale-girl sheet into device sprites and LVGL data.

The image generator sometimes renders a checkerboard instead of real alpha.
This script removes only the bright neutral background connected to each cell's
edge, preserving the white details enclosed by the character outline.
"""

from __future__ import annotations

import argparse
from collections import deque
from pathlib import Path

from PIL import Image


NAMES = (
    "offline",
    "idle",
    "thinking",
    "tool",
    "waiting",
    "done",
    "error",
    "idle_blink",
)
SIZE = 128


def is_background(pixel: tuple[int, int, int, int]) -> bool:
    r, g, b, _ = pixel
    return min(r, g, b) >= 225 and max(r, g, b) - min(r, g, b) <= 8


def remove_connected_checkerboard(image: Image.Image) -> Image.Image:
    rgba = image.convert("RGBA")
    pixels = rgba.load()
    width, height = rgba.size
    queue: deque[tuple[int, int]] = deque()
    seen = bytearray(width * height)

    def offer(x: int, y: int) -> None:
        index = y * width + x
        if not seen[index] and is_background(pixels[x, y]):
            seen[index] = 1
            queue.append((x, y))

    for x in range(width):
        offer(x, 0)
        offer(x, height - 1)
    for y in range(height):
        offer(0, y)
        offer(width - 1, y)

    while queue:
        x, y = queue.popleft()
        pixels[x, y] = (0, 0, 0, 0)
        if x:
            offer(x - 1, y)
        if x + 1 < width:
            offer(x + 1, y)
        if y:
            offer(x, y - 1)
        if y + 1 < height:
            offer(x, y + 1)
    return rgba


def fit_sprite(image: Image.Image) -> Image.Image:
    alpha = image.getchannel("A")
    bbox = alpha.getbbox()
    if bbox is None:
        raise ValueError("sprite cell is empty")
    sprite = image.crop(bbox)
    max_side = 122
    scale = min(max_side / sprite.width, max_side / sprite.height)
    size = (max(1, round(sprite.width * scale)), max(1, round(sprite.height * scale)))
    sprite = sprite.resize(size, Image.Resampling.LANCZOS)
    canvas = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    x = (SIZE - sprite.width) // 2
    y = (SIZE - sprite.height) // 2
    canvas.alpha_composite(sprite, (x, y))
    return remove_small_components(canvas)


def remove_small_components(image: Image.Image, minimum: int = 20) -> Image.Image:
    """Drop isolated generation specks while retaining real bubbles/symbols."""
    alpha = image.getchannel("A")
    pixels = alpha.load()
    width, height = alpha.size
    seen = bytearray(width * height)
    erase: list[tuple[int, int]] = []
    for y in range(height):
        for x in range(width):
            start = y * width + x
            if seen[start] or pixels[x, y] <= 8:
                continue
            seen[start] = 1
            queue = [(x, y)]
            component: list[tuple[int, int]] = []
            while queue:
                px, py = queue.pop()
                component.append((px, py))
                for nx, ny in ((px - 1, py), (px + 1, py), (px, py - 1), (px, py + 1)):
                    if not (0 <= nx < width and 0 <= ny < height):
                        continue
                    index = ny * width + nx
                    if not seen[index] and pixels[nx, ny] > 8:
                        seen[index] = 1
                        queue.append((nx, ny))
            if len(component) < minimum:
                erase.extend(component)
    rgba = image.copy()
    out = rgba.load()
    for x, y in erase:
        out[x, y] = (0, 0, 0, 0)
    return rgba


def split_sheet(sheet: Image.Image) -> list[Image.Image]:
    frames: list[Image.Image] = []
    for index in range(8):
        col = index % 4
        row = index // 4
        left = round(sheet.width * col / 4)
        right = round(sheet.width * (col + 1) / 4)
        top = round(sheet.height * row / 2)
        bottom = round(sheet.height * (row + 1) / 2)
        cell = sheet.crop((left, top, right, bottom))
        frames.append(fit_sprite(remove_connected_checkerboard(cell)))
    return frames


def emit_header(frames: list[Image.Image], output: Path) -> None:
    lines = [
        "// Generated by tools/gen_harness_whale_sprites.py; do not edit.",
        "// Eight real ARGB8888 whale-girl frames live in flash (.rodata).",
        "#pragma once",
        '#include "lvgl.h"',
        "",
        f"#define UI_HARNESS_WHALE_W {SIZE}",
        f"#define UI_HARNESS_WHALE_H {SIZE}",
        "",
    ]
    descriptors: list[str] = []
    for name, image in zip(NAMES, frames, strict=True):
        symbol = f"ui_harness_whale_{name}"
        data = bytearray()
        pixels = image.get_flattened_data() if hasattr(image, "get_flattened_data") else image.getdata()
        for r, g, b, a in pixels:
            data.extend((b, g, r, a))  # LVGL ARGB8888 byte order on ESP32.
        lines.append(f"static const uint8_t {symbol}_map[] = {{")
        for offset in range(0, len(data), 20):
            lines.append("    " + ",".join(str(v) for v in data[offset:offset + 20]) + ",")
        lines.extend([
            "};",
            f"static const lv_image_dsc_t {symbol} = {{",
            "    .header = {",
            "        .magic = LV_IMAGE_HEADER_MAGIC,",
            "        .cf = LV_COLOR_FORMAT_ARGB8888,",
            "        .flags = 0,",
            f"        .w = {SIZE}, .h = {SIZE}, .stride = {SIZE * 4},",
            "    },",
            f"    .data_size = sizeof({symbol}_map),",
            f"    .data = {symbol}_map,",
            "};",
            "",
        ])
        descriptors.append(f"    &{symbol},")
    lines.extend([
        "static const lv_image_dsc_t *const ui_harness_whale_frames[] = {",
        *descriptors,
        "};",
        "",
    ])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def save_preview(frames: list[Image.Image], output: Path) -> None:
    # The GIF is a review/community artifact. Firmware uses the same source
    # frames directly, avoiding a GIF decoder's large runtime buffer.
    preview = []
    for index, frame in enumerate(frames[:7]):
        # Two small motion beats per state make the exported preview animated.
        base = Image.new("RGBA", (144, 144), (6, 18, 30, 255))
        y = 5 if index == 5 else 8
        base.alpha_composite(frame, (8, y))
        preview.append(base)
        shifted = Image.new("RGBA", (144, 144), (6, 18, 30, 255))
        dx = -2 if index in (4, 6) else 1
        dy = -3 if index in (2, 5) else 1
        shifted.alpha_composite(frame, (8 + dx, 8 + dy))
        preview.append(shifted)
    rgb = [frame.convert("P", palette=Image.Palette.ADAPTIVE, colors=255) for frame in preview]
    output.parent.mkdir(parents=True, exist_ok=True)
    rgb[0].save(output, save_all=True, append_images=rgb[1:], duration=260, loop=0,
                disposal=2, optimize=False)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("sheet", type=Path)
    parser.add_argument("--asset-dir", type=Path,
                        default=Path("assets/harness/whale_states"))
    parser.add_argument("--header", type=Path,
                        default=Path("components/ui/presentation/src/ui_harness_sprites.h"))
    parser.add_argument("--gif", type=Path,
                        default=Path("assets/harness/blue_whale_girl_states.gif"))
    args = parser.parse_args()

    sheet = Image.open(args.sheet).convert("RGBA")
    frames = split_sheet(sheet)
    args.asset_dir.mkdir(parents=True, exist_ok=True)
    for name, frame in zip(NAMES, frames, strict=True):
        frame.save(args.asset_dir / f"{name}.png", "PNG")
    emit_header(frames, args.header)
    save_preview(frames, args.gif)
    print(f"generated {len(frames)} sprites ({SIZE}x{SIZE}), {args.header}, {args.gif}")


if __name__ == "__main__":
    main()
